// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/background.jpeg"
    | "/background.js"
    | "/icon128.png"
    | "/icon16.png"
    | "/icon48.png"
    | "/sidepanel.html"
    | "/style.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
